name: data_manager_corenlp_models
owner: ksuderman
description: Data manager for downloading Stanford CoreNLP language model JARs
long_description: |
  This data manager allows Galaxy administrators to download and install Stanford
  CoreNLP language model JAR files from Maven Central. It supports 8 languages
  with multi-select installation for use with the Stanford CoreNLP annotation tool.

  Supported languages: Arabic, Chinese, English, French, German, Hungarian, Italian, Spanish.
  Also provides the common models JAR required for coreference resolution.
homepage_url: https://stanfordnlp.github.io/CoreNLP/
remote_repository_url: https://github.com/ksuderman/data-manager-corenlp
type: unrestricted
categories:
  - Data Managers
  - Text Manipulation
  - Natural Language Processing
auto_tool_repositories:
  name_template: "{{ tool_id }}"
  description_template: "{{ tool_name }}"
  include:
    - data_manager_corenlp_models.xml
  test: false
